apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
      - name: reddit-app
        image: us-central1-docker.pkg.dev/manikesh-deployment-attempt2/deployment-repo/reddit-app:latest
        ports:
        - containerPort: 8080